version: 1.00.{build}
os: Visual Studio 2015
configuration:
- Debug
- Release
- Checked
platform:
- Win32
- x64
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  project: CharLS_VS2015.sln
  verbosity: minimal